import string

MAX_ORIGINAL_LINK_LENGTH = 2048
MAX_SHORT_LENGTH = 16
DEFAULT_SHORT_LENGTH = 6
SHORT_CHARS = string.ascii_letters + string.digits
MAX_GENERATION_ATTEMPTS = 100
FORBIDDEN_SHORT_IDS = ('files', 'api')
